### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by TheTechnologyStudio** [robinp7720/SpigotBabySitter#10]
Can you add windows 10 compatibility?

**Comment by robinp7720** [comment]
This should support every system with java 8 and nodejs installed. If you have problems installing it, I will gladly help

**Comment by TheTechnologyStudio** [comment]
Can you skype me? DuckCraftPvPFactions

**Comment by robinp7720** [comment]
No, I cannot skype but if you give me any errors I will give you text base support
